# Generated by Django 4.1 on 2023-04-18 06:03

from django.db import migrations, models
import django.db.models.deletion
import shopworld.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to=shopworld.models.getfile)),
                ('description', models.TextField(max_length=300)),
                ('status', models.BooleanField(default=False, help_text='0-show ,1-hidden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to=shopworld.models.getfile)),
                ('description', models.TextField(max_length=300)),
                ('quantity', models.IntegerField()),
                ('original_price', models.IntegerField()),
                ('selling_price', models.IntegerField()),
                ('status', models.BooleanField(default=False, help_text='0-show ,1-hidden')),
                ('trending', models.BooleanField(default=False, help_text='0-default ,1-trending')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopworld.category')),
            ],
        ),
    ]
